# fly.toml app configuration file generated for tesla-telemetry-server on 2025-04-17T08:06:22+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tesla-telemetry-server'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 800

[[services]]
  protocol = ''
  internal_port = 0

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

    [services.ports.tls_options]
      alpn = ['h2', 'http/1.1']
      versions = ['TLSv1.2', 'TLSv1.3']

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '30s'

  [[services.http_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/health'
    protocol = 'https'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
